# Generated by Django 6.0.7 on 2026-07-11 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0002_member_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='member',
            name='phone',
        ),
    ]
