# Generated by Django 6.0.7 on 2026-08-31 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0002_capability_role_volunteerprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerprofile',
            name='bio',
            field=models.TextField(blank=True, default='No bio provided.'),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='city_state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='social_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='tax_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
