# Generated by Django 6.0.7 on 2026-08-31 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0003_volunteerprofile_bio_volunteerprofile_city_state_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteerprofile',
            name='social_link',
        ),
        migrations.RemoveField(
            model_name='volunteerprofile',
            name='tax_id',
        ),
    ]
