# Generated by Django 6.0.7 on 2026-08-31 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0004_remove_volunteerprofile_social_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ministry',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_ministries', to='schedule_app.volunteerprofile'),
        ),
    ]
