# Generated by Django 6.0.7 on 2026-09-01 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0005_ministry_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('regular', 'Regular Service'), ('scheduled', 'Scheduled Event'), ('big', 'Big Event')], default='regular', max_length=50),
        ),
    ]
