# Generated by Django 6.0.7 on 2026-09-02 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0006_event_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='offices',
            field=models.ManyToManyField(blank=True, related_name='events', to='schedule_app.ministry'),
        ),
    ]
