# Generated by Django 6.0.7 on 2026-07-13 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0006_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
