# Generated by Django 6.0.7 on 2026-09-02 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0008_unavailability'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_volunteers', models.ManyToManyField(blank=True, related_name='assigned_jobs', to='schedule_app.volunteerprofile')),
                ('ministry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='schedule_app.ministry')),
                ('team_leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_jobs', to='schedule_app.volunteerprofile')),
            ],
            options={
                'verbose_name': 'Department Job',
                'verbose_name_plural': 'Department Jobs',
                'ordering': ['title'],
            },
        ),
    ]
