# Generated by Django 6.0.7 on 2026-07-16 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0008_activity_member_activity_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-created_at']},
        ),
    ]
