# Generated by Django 6.0.7 on 2026-09-02 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0009_departmentjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shifts', to='schedule_app.departmentjob'),
        ),
    ]
