# Generated by Django 6.0.7 on 2026-07-23 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0009_alter_activity_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('MEMBER', 'Member')], default='MEMBER', max_length=10),
        ),
    ]
