# Generated by Django 6.0.7 on 2026-09-19 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0011_volunteerprofile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerprofile',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
